---
- hosts: all
  user: root
  tasks:
    - name: Docker 用 yum リポジトリの追加
      yum_repository:
        name: dockerrepo
        description: Docker Repository
        baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
        enabled: yes
        gpgkey: https://yum.dockerproject.org/gpg
        gpgcheck: yes
      become: True

    - name: docker-engine のインストール
      yum: name=docker-engine enablerepo=dockerrepo state=installed

    - name: dockerサービスを開始
      service: name=docker state=started
